{{- if .Values.provider.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kepimetheus.secretName" . }}
  labels:
    {{- include "kepimetheus.labels" . | nindent 4 }}
  {{- with .Values.provider.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.provider.secret.stringData.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.provider.secret.stringData.AWS_SECRET_ACCESS_KEY }}
{{- end }}